[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 20

[[main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 30

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 40
