baseURL = "https://hugo.simplecss.org"
languageCode = "en-us"
title = "Simple Hugo - A Hugo site powered by Simple.css"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 40

[permalinks]
  posts = "/:title/"

[markup]
  [markup.highlight]
    style = "monokailight"

