baseURL = "https://hugo.simplecss.org"
languageCode = "en-us"
title = "Simple Hugo - A Hugo site powered by Simple.css"


[permalinks]
  posts = "/:title/"

[markup]
  [markup.highlight]
    style = "monokailight"

