baseURL = "https://hugo.simplecss.org"
languageCode = "en-us"
title = "This is my Hugo website that is running Simple.css"


[permalinks]
  posts = "/:title/"

[markup]
  [markup.highlight]
    style = "monokailight"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
